name: Slither Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Slither
      uses: crytic/slither-action@v0.3.0
      with:
        target: .
        sarif: results.sarif